### ISSUE TITLE
Use proper make install for AVR-LibC

### ISSUE THREAD

**Issue by sprintersb** [ZakKemble/avr-gcc-build#10]
The build script does cumbersome commands like

`cp -r "$PREFIX_LIBC"/* "$PREFIX_GCC_LINUX"`

in order to "install" AVR-LibC. The proper way to install it in a location other then `--prefix` is:

`make install prefix="${PREFIX_GCC_LINUX}"`

etc.

**Comment by ZakKemble** [comment]
Sorted 👍
